export const countries = [
  { key: 0, name: "World" },
  { key: 1, name: "USA" },
  { key: 2, name: "India" },
  { key: 3, name: "Brazil" },
  { key: 4, name: "France" },
  { key: 5, name: "Russia" },
  { key: 6, name: "Turkey" },
  { key: 7, name: "UK" },
  { key: 8, name: "Argentina" },
  { key: 9, name: "Italy" },
  { key: 10, name: "Colombia" },
  { key: 11, name: "Spain" },
  { key: 12, name: "Germany" },
  { key: 13, name: "Iran" },
  { key: 14, name: "Poland" },
  { key: 15, name: "Mexico" },
  { key: 16, name: "Ukraine" },
  { key: 17, name: "Indonesia" },
  { key: 18, name: "Peru" },
  { key: 19, name: "South Africa" },
  { key: 20, name: "Netherlands" },
  { key: 21, name: "Czechia" },
  { key: 22, name: "Chile" },
  { key: 23, name: "Canada" },
  { key: 24, name: "Philippines" },
  { key: 25, name: "Iraq" },
  { key: 26, name: "Sweden" },
  { key: 27, name: "Belgium" },
  { key: 28, name: "Romania" },
  { key: 29, name: "Pakistan" },
  { key: 30, name: "Bangladesh" },
  { key: 31, name: "Portugal" },
  { key: 32, name: "Israel" },
  { key: 33, name: "Hungary" },
  { key: 34, name: "Japan" },
  { key: 35, name: "Jordan" },
  { key: 36, name: "Malaysia" },
  { key: 37, name: "Serbia" },
  { key: 38, name: "Switzerland" },
  { key: 39, name: "Austria" },
  { key: 40, name: "Nepal" },
  { key: 41, name: "UAE" },
  { key: 42, name: "Lebanon" },
  { key: 43, name: "Morocco" },
  { key: 44, name: "Saudi Arabia" },
  { key: 45, name: "Ecuador" },
  { key: 46, name: "Bolivia" },
  { key: 47, name: "Bulgaria" },
  { key: 48, name: "Greece" },
  { key: 49, name: "Kazakhstan" },
  { key: 50, name: "Paraguay" },
  { key: 51, name: "Belarus" },
  { key: 52, name: "Tunisia" },
  { key: 53, name: "Panama" },
  { key: 54, name: "Slovakia" },
  { key: 55, name: "Uruguay" },
  { key: 56, name: "Georgia" },
  { key: 57, name: "Costa Rica" },
  { key: 58, name: "Croatia" },
  { key: 59, name: "Kuwait" },
  { key: 60, name: "Azerbaijan" },
  { key: 61, name: "Dominican Republic" },
  { key: 62, name: "Palestine" },
  { key: 63, name: "Denmark" },
  { key: 64, name: "Guatemala" },
  { key: 65, name: "Egypt" },
  { key: 66, name: "Lithuania" },
  { key: 67, name: "Ethiopia" },
  { key: 68, name: "Ireland" },
  { key: 69, name: "Venezuela" },
  { key: 70, name: "Bahrain" },
  { key: 71, name: "Oman" },
  { key: 72, name: "Honduras" },
  { key: 73, name: "Slovenia" },
  { key: 74, name: "Moldova" },
  { key: 75, name: "Sri Lanka" },
  { key: 76, name: "Thailand" },
  { key: 77, name: "Armenia" },
  { key: 78, name: "Qatar" },
  { key: 79, name: "Bosnia and Herzegovina" },
  { key: 80, name: "Libya" },
  { key: 81, name: "Kenya" },
  { key: 82, name: "Cuba" },
  { key: 83, name: "Nigeria" },
  { key: 84, name: "North Macedonia" },
  { key: 85, name: "S. Korea" },
  { key: 86, name: "Myanmar" },
  { key: 87, name: "Zambia" },
  { key: 88, name: "Algeria" },
  { key: 89, name: "Latvia" },
  { key: 90, name: "Albania" },
  { key: 91, name: "Estonia" },
  { key: 92, name: "Norway" },
  { key: 93, name: "Kyrgyzstan" },
  { key: 94, name: "Afghanistan" },
  { key: 95, name: "Mongolia" },
  { key: 96, name: "Uzbekistan" },
  { key: 97, name: "Montenegro" },
  { key: 98, name: "Ghana" },
  { key: 99, name: "Finland" },
  { key: 100, name: "Namibia" },
  { key: 101, name: "Cameroon" },
  { key: 102, name: "Uganda" },
  { key: 103, name: "El Salvador" },
  { key: 104, name: "Mozambique" },
  { key: 105, name: "Cyprus" },
  { key: 106, name: "Maldives" },
  { key: 107, name: "Luxembourg" },
  { key: 108, name: "Botswana" },
  { key: 109, name: "Singapore" },
  { key: 110, name: "Jamaica" },
  { key: 111, name: "Ivory Coast" },
  { key: 112, name: "Cambodia" },
  { key: 113, name: "Zimbabwe" },
  { key: 114, name: "Senegal" },
  { key: 115, name: "Madagascar" },
  { key: 116, name: "DRC" },
  { key: 117, name: "Angola" },
  { key: 118, name: "Sudan" },
  { key: 119, name: "Rwanda" },
  { key: 120, name: "Malawi" },
  { key: 121, name: "Cabo Verde" },
  { key: 122, name: "Trinidad and Tobago" },
  { key: 123, name: "Malta" },
  { key: 124, name: "Australia" },
  { key: 125, name: "Réunion" },
  { key: 126, name: "French Guiana" },
  { key: 127, name: "Syria" },
  { key: 128, name: "Gabon" },
  { key: 129, name: "Guinea" },
  { key: 130, name: "Suriname" },
  { key: 131, name: "Mauritania" },
  { key: 132, name: "Guyana" },
  { key: 133, name: "Mayotte" },
  { key: 134, name: "Eswatini" },
  { key: 135, name: "French Polynesia" },
  { key: 136, name: "Haiti" },
  { key: 137, name: "Papua New Guinea" },
  { key: 138, name: "Guadeloupe" },
  { key: 139, name: "Vietnam" },
  { key: 140, name: "Seychelles" },
  { key: 141, name: "Somalia" },
  { key: 142, name: "Taiwan" },
  { key: 143, name: "Mali" },
  { key: 144, name: "Andorra" },
  { key: 145, name: "Togo" },
  { key: 146, name: "Burkina Faso" },
  { key: 147, name: "Tajikistan" },
  { key: 148, name: "Belize" },
  { key: 149, name: "Congo" },
  { key: 150, name: "Bahamas" },
  { key: 151, name: "Curaçao" },
  { key: 152, name: "Martinique" },
  { key: 153, name: "Hong Kong" },
  { key: 154, name: "Djibouti" },
  { key: 155, name: "Lesotho" },
  { key: 156, name: "Aruba" },
  { key: 157, name: "South Sudan" },
  { key: 158, name: "Timor-Leste" },
  { key: 159, name: "Equatorial Guinea" },
  { key: 160, name: "Benin" },
  { key: 161, name: "Nicaragua" },
  { key: 162, name: "CAR" },
  { key: 163, name: "Yemen" },
  { key: 164, name: "Iceland" },
  { key: 165, name: "Gambia" },
  { key: 166, name: "Eritrea" },
  { key: 167, name: "Niger" },
  { key: 168, name: "Burundi" },
  { key: 169, name: "Sierra Leone" },
  { key: 170, name: "Saint Lucia" },
  { key: 171, name: "San Marino" },
  { key: 172, name: "Chad" },
  { key: 173, name: "Gibraltar" },
  { key: 174, name: "Channel Islands" },
  { key: 175, name: "Barbados" },
  { key: 176, name: "Comoros" },
  { key: 177, name: "Guinea-Bissau" },
  { key: 178, name: "Fiji" },
  { key: 179, name: "Liberia" },
  { key: 180, name: "Liechtenstein" },
  { key: 181, name: "New Zealand" },
  { key: 182, name: "Sint Maarten" },
  { key: 183, name: "Monaco" },
  { key: 184, name: "Bermuda" },
  { key: 185, name: "Turks and Caicos" },
  { key: 186, name: "Sao Tome and Principe" },
  { key: 187, name: "Saint Martin" },
  { key: 188, name: "St. Vincent Grenadines" },
  { key: 189, name: "Laos" },
  { key: 190, name: "Bhutan" },
  { key: 191, name: "Mauritius" },
  { key: 192, name: "Caribbean Netherlands" },
  { key: 193, name: "Isle of Man" },
  { key: 194, name: "Antigua and Barbuda" },
  { key: 195, name: "St. Barth" },
  { key: 196, name: "Faeroe Islands" },
  { key: 197, name: "Diamond Princess" },
  { key: 198, name: "Cayman Islands" },
  { key: 199, name: "Tanzania" },
  { key: 200, name: "Wallis and Futuna" },
  { key: 201, name: "Saint Kitts and Nevis" },
  { key: 202, name: "British Virgin Islands" },
  { key: 203, name: "Brunei" },
  { key: 204, name: "Dominica" },
  { key: 205, name: "Grenada" },
  { key: 206, name: "New Caledonia" },
  { key: 207, name: "Anguilla" },
  { key: 208, name: "Falkland Islands" },
  { key: 209, name: "Macao" },
  { key: 210, name: "Greenland" },
  { key: 211, name: "Vatican City" },
  { key: 212, name: "Saint Pierre Miquelon" },
  { key: 213, name: "Montserrat" },
  { key: 214, name: "Solomon Islands" },
  { key: 215, name: "Western Sahara" },
  { key: 216, name: "MS Zaandam" },
  { key: 217, name: "Vanuatu" },
  { key: 218, name: "Marshall Islands" },
  { key: 219, name: "Samoa" },
  { key: 220, name: "Saint Helena" },
  { key: 221, name: "Micronesia" },
  { key: 222, name: "China" },
];
